version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV}
                APP_DEBUG: ${APP_DEBUG}
                APP_URL: ${APP_URL}
                DB_CONNECTION: ${DB_CONNECTION}
                DB_HOST: ${DB_HOST}
                DB_PORT: ${DB_PORT}
                DB_DATABASE: ${DB_DATABASE}
                DB_USERNAME: ${DB_USERNAME}
                DB_PASSWORD: ${DB_PASSWORD}
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        env_file:
            - .env

    db:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
